"""empty message

Revision ID: f668dc395748
Revises: 
Create Date: 2024-01-05 17:54:30.647494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f668dc395748'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_serviceName', sa.String(length=128), nullable=False),
    sa.Column('s_description', sa.String(length=255), nullable=False),
    sa.Column('s_price', sa.String(length=128), nullable=False),
    sa.Column('s_providerID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['s_providerID'], ['service__provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_userID', sa.Integer(), nullable=True),
    sa.Column('b_serviceID', sa.Integer(), nullable=True),
    sa.Column('b_bookingDate', sa.String(length=128), nullable=False),
    sa.Column('b_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['b_serviceID'], ['services.id'], ),
    sa.ForeignKeyConstraint(['b_userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('p_userID', sa.Integer(), nullable=True),
    sa.Column('p_bookingID', sa.Integer(), nullable=True),
    sa.Column('p_amount', sa.String(length=128), nullable=False),
    sa.Column('p_paymentDate', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['p_bookingID'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['p_userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('booking')
    op.drop_table('services')
    # ### end Alembic commands ###
